name: Main CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  build:
    uses: sjunaiduk/AutomatedLearningSystem/.github/workflows/build.yml@main

  test:
    needs: build
    uses: sjunaiduk/AutomatedLearningSystem/.github/workflows/test.yml@main
