name: Test .NET Project

on:
  workflow_call:
  
permissions:
  contents: read
  actions: read
  checks: write
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Specify your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Run Tests
      run: dotnet test --logger "trx;LogFileName=test_results.trx"
      continue-on-error: true # This allows the step to "pass" even if tests fail


    - name: Process Test Results
      uses: dorny/test-reporter@v1
      with:
        name: .NET Test Results
        path: '**/test_results.trx'
        reporter: 'dotnet-trx'
        fail-on-error: true


