name: Test .NET Project

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Specify your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Test
      run: dotnet test --no-restore
